## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - gfortran
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999

# (tests will run but not make your overall status red)
matrix:
 allow_failures:
 - julia: nightly

after_success:
- julia -e 'cd(Pkg.dir("MyPkg")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'